image: alpine/edge
packages:
  - make
  - rsync
sources:
  - https://git.sr.ht/~sumner/quadratic-solver
secrets:
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
environment:
  REPO_NAME: quadratic-solver
  WEBSITE_NAME: qs.sumnerevans.com
triggers:
  - action: email
    condition: failure
    to: ~sumner/public-inbox@lists.sr.ht
tasks:
  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  - build: |
      make build

  - rsync: |
      # Skip if not on master
      git branch --contains | grep master || echo "Skipping deploy since not on master"
      git branch --contains | grep master || complete-build

      ssh-keyscan bespin.sumnerevans.com >> ~/.ssh/known_hosts

      # Copy the website over to the server
      ssh root@bespin.sumnerevans.com "mkdir -p /var/www/${WEBSITE_NAME}" &&
      rsync -vr --delete-after builds/ root@bespin.sumnerevans.com:/var/www/${WEBSITE_NAME}
